### ISSUE TITLE
订阅 bangumi.tv 的个人收藏或时间线 RSS 的时候会报错

### ISSUE THREAD

**Issue by CercisSuoh** [RimoChan/rimo-rss-reader#3]
报错提示如下
```bash
[2023-01-28 22:23:17.399063]【BangumiTest】访问 https://bgm.tv/feed/user/261227/timeline
 * Serving Flask app '__main__'
 * Debug mode: off
ERROR:root:Object of type SAXParseException is not JSON serializable
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_rss_reader/__main__.py", line 141, in 循环
    es = get_feed(i.url)
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_rss_reader/__main__.py", line 101, in get_feed
    全局存储['meta'] = {**全局存储.get('meta', {}), url: feed}
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_storage/__init__.py", line 109, in __setitem__
    return super().__setitem__(k, self.serialize(v))
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_storage/__init__.py", line 36, in <lambda>
    lambda x: json.dumps(x, sort_keys=True, ensure_ascii=False, separators=(',', ':')).encode('utf8'),
  File "/home/ubuntu/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SAXParseException is not JSON serializable
[2023-01-28 22:23:19.655901]【BangumiTest】访问 https://bgm.tv/feed/user/261227/interests
ERROR:root:Object of type SAXParseException is not JSON serializable
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_rss_reader/__main__.py", line 141, in 循环
    es = get_feed(i.url)
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_rss_reader/__main__.py", line 101, in get_feed
    全局存储['meta'] = {**全局存储.get('meta', {}), url: feed}
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_storage/__init__.py", line 109, in __setitem__
    return super().__setitem__(k, self.serialize(v))
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/rimo_storage/__init__.py", line 36, in <lambda>
    lambda x: json.dumps(x, sort_keys=True, ensure_ascii=False, separators=(',', ':')).encode('utf8'),
  File "/home/ubuntu/miniforge3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/miniforge3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SAXParseException is not JSON serializable
[2023-01-28 22:23:22.906600]【奇怪的东西】访问 https://rsshub.app/pork-price
https://rsshub.app/pork-price 更新完成。获取 3 个条目，其中id重复 3 个，3 个条目内容也相同。
```
配置.yaml 附上
```yaml
别的电脑也可以看: True
端口号: 23333
windows通知: False
订阅组:
  BangumiTest:
    - name: Timeline
      url: https://bgm.tv/feed/user/261227/timeline
    - name: Interests
      url: https://bgm.tv/feed/user/261227/interests
  奇怪的东西:
    - name: 猪肉价格
      url: https://rsshub.app/pork-price
```

**Comment by RimoChan** [comment]
嗯，我今晚看1看

**Comment by RimoChan** [comment]
修好了，似乎是bangumi不让我用空的header访问

**Comment by RimoChan** [comment]
你重新安装一次应该就可以了
